### ISSUE TITLE
Convert map tabs into check boxes

### ISSUE THREAD

**Issue by AudioPixie** [AudioPixie/TPRTracker#25]
So overworld, bug, and poe checks can all be on the map at the same time. Would want to still have the option of the original exclusive behavior. Checks would need to be moved to avoid overlap and dungeon lists would need to be reworked. Likely would put all checks on the same list with the poes at the bottom.

**Comment by laurentdupin** [comment]
Just to add my input on that subject, I did a run with a modified version of the tracker (which you can find on [my fork of the repository](https://github.com/laurentdupin/TPRTracker)) in which I did put all the checks on one map and also added howling stones and I think it makes the whole experience much better as you are not constantly switching between tabs. 

When it comes to overlapping checks, I think it is fine to have some of them not be in the right place as long as they are relatively positioned "correctly" compared to the other checks in the same area. In the area where the positioning matters like the different Fields and Gerudo Desert, there is enough space so that overlapping is not really an issue there.

As for Poes, I did the fastest thing based on how you did set up the map which is to take the buttons from both the overworld and poe tab and lay them side by side. I think displaying the numbers of available checks on the map for both types is actually a good thing but if you want to keep just one button on the map, I would say that tab (with maybe the number of checks for each type displayed on the tab button) in the bottom left check list would be better than just putting the poes at the end of the list.

Finally, I think having howling stones is an ok addition, at least as a reminder when you are in the area that they exist. In terms of logic, I did link them to the logic of the associated Golden Wolf but having a logic based on if you can access the area + having the shadow crystal is probably better. I did though not add them to the save file as I did not want to spend more time on the issue but I think they are pretty much a necessary addition if they are added.

![image](https://github.com/AudioPixie/TPRTracker/assets/48155177/ae5e02b2-ad5b-4a60-9be6-e22f15b96ef0)

**Comment by AudioPixie** [comment]
Going to check this out, thank you!

**Comment by AudioPixie** [comment]
End result functions a bit different but this is reflected in 1.2.1. Thank you for getting this kick started!! The howling stone contribution will likely be up for the next update :P ty again!!
